name: kizuki
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Authentication
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.2
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  firebase_app_check: ^0.2.1+13
  # Storage
  cloud_firestore: ^4.15.2
  firebase_ui_firestore: ^1.6.1
  firebase_storage: ^11.6.5
  # State
  provider: ^6.1.1
  # Router
  go_router: ^13.0.1
  # External
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  get_it: ^7.6.7
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_downloader: ^1.11.6
  permission_handler: ^11.2.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
