// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuSapnXGtVWKEIxxi_eqdYNJn76K0rCI',
    appId: '1:401245033042:web:2573dfe9fb0ac3c5a2858b',
    messagingSenderId: '401245033042',
    projectId: 'kizuki-walls',
    authDomain: 'kizuki-walls.firebaseapp.com',
    storageBucket: 'kizuki-walls.appspot.com',
    measurementId: 'G-V8S8DN4VFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ4A2aBAepSFHSGZaCpeKtDUb79MBDA3c',
    appId: '1:401245033042:android:1dc2c00fbf23ba94a2858b',
    messagingSenderId: '401245033042',
    projectId: 'kizuki-walls',
    storageBucket: 'kizuki-walls.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyFk9z09dE0zijRDqgkk2RF9DR5s8aJho',
    appId: '1:401245033042:ios:ff7d277f1c84a8a2a2858b',
    messagingSenderId: '401245033042',
    projectId: 'kizuki-walls',
    storageBucket: 'kizuki-walls.appspot.com',
    androidClientId: '401245033042-thobkolbc07eb32660t2185eb6kglki4.apps.googleusercontent.com',
    iosClientId: '401245033042-nauutbefckc4gs76cj4vtaabv39n63f1.apps.googleusercontent.com',
    iosBundleId: 'com.kizuki.kizuki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyFk9z09dE0zijRDqgkk2RF9DR5s8aJho',
    appId: '1:401245033042:ios:7ea6cdd7c239d3d9a2858b',
    messagingSenderId: '401245033042',
    projectId: 'kizuki-walls',
    storageBucket: 'kizuki-walls.appspot.com',
    androidClientId: '401245033042-thobkolbc07eb32660t2185eb6kglki4.apps.googleusercontent.com',
    iosClientId: '401245033042-16nr12hosa57qsl0l0og9l0tk22om36n.apps.googleusercontent.com',
    iosBundleId: 'com.kizuki.kizuki.RunnerTests',
  );
}
